/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

import javax.swing.JMenuItem;

/**
 *
 * @author 12212
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        jLabel1.setText("Sistema de gestión de servicios veterinarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        GestionClientes = new javax.swing.JMenu();
        RegistrarCliente = new javax.swing.JMenuItem();
        ModificarCliente = new javax.swing.JMenuItem();
        EliminarCliente = new javax.swing.JMenuItem();
        GestionMascotas = new javax.swing.JMenu();
        RegistrarMascota = new javax.swing.JMenuItem();
        ModificarMascota = new javax.swing.JMenuItem();
        EliminarMascota = new javax.swing.JMenuItem();
        GestionCitas = new javax.swing.JMenu();
        RealizarCita = new javax.swing.JMenuItem();
        EliminarCita = new javax.swing.JMenuItem();
        ConfirmarCita = new javax.swing.JMenuItem();
        VistaDatos = new javax.swing.JMenu();
        MostrarClientes = new javax.swing.JMenuItem();
        MostrarMascotas = new javax.swing.JMenuItem();
        MostrarHistorialServicios = new javax.swing.JMenuItem();
        Funcionalidades = new javax.swing.JMenu();
        Test = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setEnabled(false);

        GestionClientes.setMnemonic('f');
        GestionClientes.setText("Gestionar Clientes");

        RegistrarCliente.setMnemonic('o');
        RegistrarCliente.setText("Registrar Cliente");
        RegistrarCliente.setActionCommand("RegistrarCliente");
        RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClienteActionPerformed(evt);
            }
        });
        GestionClientes.add(RegistrarCliente);
        RegistrarCliente.getAccessibleContext().setAccessibleName("RegistrarCliente");

        ModificarCliente.setMnemonic('s');
        ModificarCliente.setText("Modificar Cliente");
        ModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarClienteActionPerformed(evt);
            }
        });
        GestionClientes.add(ModificarCliente);

        EliminarCliente.setMnemonic('a');
        EliminarCliente.setText("Eliminar Cliente");
        EliminarCliente.setToolTipText("");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });
        GestionClientes.add(EliminarCliente);

        menuBar.add(GestionClientes);

        GestionMascotas.setMnemonic('e');
        GestionMascotas.setText("Gestionar Mascotas");

        RegistrarMascota.setMnemonic('t');
        RegistrarMascota.setText("Registrar Mascota");
        RegistrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarMascotaActionPerformed(evt);
            }
        });
        GestionMascotas.add(RegistrarMascota);

        ModificarMascota.setMnemonic('y');
        ModificarMascota.setText("Modificar Mascota");
        ModificarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMascotaActionPerformed(evt);
            }
        });
        GestionMascotas.add(ModificarMascota);

        EliminarMascota.setMnemonic('p');
        EliminarMascota.setText("Eliminar Mascota");
        EliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMascotaActionPerformed(evt);
            }
        });
        GestionMascotas.add(EliminarMascota);

        menuBar.add(GestionMascotas);

        GestionCitas.setMnemonic('h');
        GestionCitas.setText("Gestionar Citas");

        RealizarCita.setMnemonic('c');
        RealizarCita.setText("Realizar Cita");
        RealizarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCitaActionPerformed(evt);
            }
        });
        GestionCitas.add(RealizarCita);

        EliminarCita.setMnemonic('c');
        EliminarCita.setText("Eliminar Cita");
        EliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCitaActionPerformed(evt);
            }
        });
        GestionCitas.add(EliminarCita);

        ConfirmarCita.setMnemonic('c');
        ConfirmarCita.setText("Confirmar Cita");
        ConfirmarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarCitaActionPerformed(evt);
            }
        });
        GestionCitas.add(ConfirmarCita);

        menuBar.add(GestionCitas);

        VistaDatos.setMnemonic('h');
        VistaDatos.setText("Vista de datos");

        MostrarClientes.setMnemonic('c');
        MostrarClientes.setText("Mostrar Clientes");
        MostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarClientesActionPerformed(evt);
            }
        });
        VistaDatos.add(MostrarClientes);

        MostrarMascotas.setMnemonic('a');
        MostrarMascotas.setText("Mostrar Mascotas");
        MostrarMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarMascotasActionPerformed(evt);
            }
        });
        VistaDatos.add(MostrarMascotas);

        MostrarHistorialServicios.setMnemonic('a');
        MostrarHistorialServicios.setText("Mostrar Historial de Servicios");
        MostrarHistorialServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarHistorialServiciosActionPerformed(evt);
            }
        });
        VistaDatos.add(MostrarHistorialServicios);

        menuBar.add(VistaDatos);

        Funcionalidades.setMnemonic('h');
        Funcionalidades.setText("Funcionalidades");

        Test.setMnemonic('c');
        Test.setText("Test");
        Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestActionPerformed(evt);
            }
        });
        Funcionalidades.add(Test);

        menuBar.add(Funcionalidades);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getRegistrarCliente(){
        return RegistrarCliente;
    }
    
    public JMenuItem getModificarCliente(){
        return ModificarCliente;
    }
    
    public JMenuItem getEliminarCliente(){
        return EliminarCliente;
    }
    
    public JMenuItem getRegistrarMascota(){
        return RegistrarMascota;
    }
    
    public JMenuItem getModificarMascota(){
        return ModificarMascota;
    }
    
    public JMenuItem getEliminarMascota(){
        return EliminarMascota;
    }
    
    public JMenuItem getRealizarCita(){
        return RealizarCita;
    }
    
    public JMenuItem getEliminarCita(){
        return EliminarCita;
    }
    
    public JMenuItem getConfirmarCita(){
        return ConfirmarCita;
    }
    
    public JMenuItem getMostrarClientes(){
        return MostrarClientes;
    }
    
    public JMenuItem getMostrarMascotas(){
        return MostrarMascotas;
    }
    
    public JMenuItem getMostrarHistorialServicios(){
        return MostrarHistorialServicios;
    }
    
    private void RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarClienteActionPerformed

    private void ModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarClienteActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void RegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarMascotaActionPerformed

    private void ModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMascotaActionPerformed

    private void EliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMascotaActionPerformed

    private void RealizarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RealizarCitaActionPerformed

    private void EliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarCitaActionPerformed

    private void ConfirmarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarCitaActionPerformed

    private void MostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarClientesActionPerformed

    private void MostrarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarMascotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarMascotasActionPerformed

    private void MostrarHistorialServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarHistorialServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarHistorialServiciosActionPerformed

    private void TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConfirmarCita;
    private javax.swing.JMenuItem EliminarCita;
    private javax.swing.JMenuItem EliminarCliente;
    private javax.swing.JMenuItem EliminarMascota;
    private javax.swing.JMenu Funcionalidades;
    private javax.swing.JMenu GestionCitas;
    private javax.swing.JMenu GestionClientes;
    private javax.swing.JMenu GestionMascotas;
    private javax.swing.JMenuItem ModificarCliente;
    private javax.swing.JMenuItem ModificarMascota;
    private javax.swing.JMenuItem MostrarClientes;
    private javax.swing.JMenuItem MostrarHistorialServicios;
    private javax.swing.JMenuItem MostrarMascotas;
    private javax.swing.JMenuItem RealizarCita;
    private javax.swing.JMenuItem RegistrarCliente;
    private javax.swing.JMenuItem RegistrarMascota;
    private javax.swing.JMenuItem Test;
    private javax.swing.JMenu VistaDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
