/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package view;

/**
 *
 * @author 12212
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        GestionClientesMenu = new javax.swing.JMenu();
        RegistrarClienteItem = new javax.swing.JMenuItem();
        ModificarClienteItem = new javax.swing.JMenuItem();
        EliminarClienteItem = new javax.swing.JMenuItem();
        GestionMascotasMenu = new javax.swing.JMenu();
        RegistrarMascotaItem = new javax.swing.JMenuItem();
        ModificarMascotaItem = new javax.swing.JMenuItem();
        EliminarMascotaItem = new javax.swing.JMenuItem();
        GestionCitasMenu = new javax.swing.JMenu();
        RealizarCitaItem = new javax.swing.JMenuItem();
        ModificarCitaItem = new javax.swing.JMenuItem();
        EliminarCitaItem = new javax.swing.JMenuItem();
        ConfirmarCitaItem = new javax.swing.JMenuItem();
        VistaDatosMenu = new javax.swing.JMenu();
        MostrarClientesItem = new javax.swing.JMenuItem();
        MostrarMascotasItem = new javax.swing.JMenuItem();
        MostrarHistorialServiciosItem = new javax.swing.JMenuItem();
        FuncionalidadesMenu = new javax.swing.JMenu();
        TestItem = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GestionClientesMenu.setMnemonic('f');
        GestionClientesMenu.setText("Gestionar Clientes");

        RegistrarClienteItem.setMnemonic('o');
        RegistrarClienteItem.setText("Registrar Cliente");
        RegistrarClienteItem.setActionCommand("Registrar Cliente");
        RegistrarClienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarClienteItemActionPerformed(evt);
            }
        });
        GestionClientesMenu.add(RegistrarClienteItem);

        ModificarClienteItem.setMnemonic('s');
        ModificarClienteItem.setText("Modificar Cliente");
        GestionClientesMenu.add(ModificarClienteItem);

        EliminarClienteItem.setMnemonic('a');
        EliminarClienteItem.setText("Eliminar Cliente");
        EliminarClienteItem.setToolTipText("");
        GestionClientesMenu.add(EliminarClienteItem);

        menuBar.add(GestionClientesMenu);

        GestionMascotasMenu.setMnemonic('e');
        GestionMascotasMenu.setText("Gestionar Mascotas");

        RegistrarMascotaItem.setMnemonic('t');
        RegistrarMascotaItem.setText("Registrar Mascota");
        GestionMascotasMenu.add(RegistrarMascotaItem);

        ModificarMascotaItem.setMnemonic('y');
        ModificarMascotaItem.setText("Modificar Mascota");
        GestionMascotasMenu.add(ModificarMascotaItem);

        EliminarMascotaItem.setMnemonic('p');
        EliminarMascotaItem.setText("Eliminar Mascota");
        GestionMascotasMenu.add(EliminarMascotaItem);

        menuBar.add(GestionMascotasMenu);

        GestionCitasMenu.setMnemonic('h');
        GestionCitasMenu.setText("Gestionar Citas");

        RealizarCitaItem.setMnemonic('c');
        RealizarCitaItem.setText("Realizar Cita");
        GestionCitasMenu.add(RealizarCitaItem);

        ModificarCitaItem.setMnemonic('a');
        ModificarCitaItem.setText("Modificar Cita");
        GestionCitasMenu.add(ModificarCitaItem);

        EliminarCitaItem.setMnemonic('c');
        EliminarCitaItem.setText("Eliminar Cita");
        GestionCitasMenu.add(EliminarCitaItem);

        ConfirmarCitaItem.setMnemonic('c');
        ConfirmarCitaItem.setText("Confirmar Cita");
        GestionCitasMenu.add(ConfirmarCitaItem);

        menuBar.add(GestionCitasMenu);

        VistaDatosMenu.setMnemonic('h');
        VistaDatosMenu.setText("Vista de datos");

        MostrarClientesItem.setMnemonic('c');
        MostrarClientesItem.setText("Mostrar Clientes");
        VistaDatosMenu.add(MostrarClientesItem);

        MostrarMascotasItem.setMnemonic('a');
        MostrarMascotasItem.setText("Mostrar Mascotas");
        VistaDatosMenu.add(MostrarMascotasItem);

        MostrarHistorialServiciosItem.setMnemonic('c');
        MostrarHistorialServiciosItem.setText("Mostrar Historial de Servicios");
        MostrarHistorialServiciosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarHistorialServiciosItemActionPerformed(evt);
            }
        });
        VistaDatosMenu.add(MostrarHistorialServiciosItem);

        menuBar.add(VistaDatosMenu);

        FuncionalidadesMenu.setMnemonic('h');
        FuncionalidadesMenu.setText("Funcionalidades");

        TestItem.setMnemonic('c');
        TestItem.setText("Test");
        FuncionalidadesMenu.add(TestItem);

        menuBar.add(FuncionalidadesMenu);

        ExitMenu.setMnemonic('h');
        ExitMenu.setText("Salir");
        menuBar.add(ExitMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarClienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarClienteItemActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarClienteItemActionPerformed

    private void MostrarHistorialServiciosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarHistorialServiciosItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarHistorialServiciosItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConfirmarCitaItem;
    private javax.swing.JMenuItem EliminarCitaItem;
    private javax.swing.JMenuItem EliminarClienteItem;
    private javax.swing.JMenuItem EliminarMascotaItem;
    private javax.swing.JMenu ExitMenu;
    private javax.swing.JMenu FuncionalidadesMenu;
    private javax.swing.JMenu GestionCitasMenu;
    private javax.swing.JMenu GestionClientesMenu;
    private javax.swing.JMenu GestionMascotasMenu;
    private javax.swing.JMenuItem ModificarCitaItem;
    private javax.swing.JMenuItem ModificarClienteItem;
    private javax.swing.JMenuItem ModificarMascotaItem;
    private javax.swing.JMenuItem MostrarClientesItem;
    private javax.swing.JMenuItem MostrarHistorialServiciosItem;
    private javax.swing.JMenuItem MostrarMascotasItem;
    private javax.swing.JMenuItem RealizarCitaItem;
    private javax.swing.JMenuItem RegistrarClienteItem;
    private javax.swing.JMenuItem RegistrarMascotaItem;
    private javax.swing.JMenuItem TestItem;
    private javax.swing.JMenu VistaDatosMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
